<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="addcategory.aspx.cs" Inherits="addcategory" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
        {
            height: 52px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <center>
<table width="40%">
<tr><td align="center" colspan="2"><asp:Label ID="Label1" runat="server" 
        Text="ADD CATIGORY" Font-Bold="True" Font-Italic="True"></asp:Label></td></tr>
<tr><td><asp:Label ID="Label2" runat="server" Text="NAME"></asp:Label></td>
<td><asp:TextBox ID="TextBox1" runat="server" Width="237px"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<asp:Button ID="Button1" runat="server" 
        Text="ADDED" onclick="Button1_Click"  /></td>
</tr>
<tr><td align="center" colspan="2" >
    <asp:Label ID="lblerror" runat="server" Font-Bold="True" Font-Italic="True" 
        ForeColor="Red"></asp:Label></td>
</tr>
<tr><td align="center" colspan="2" >
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="cid"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataSourceID="SqlDataSource1" Width="60%">
        <Columns>
            <asp:BoundField DataField="cid" HeaderText="CID" InsertVisible="False" 
                ReadOnly="True" SortExpression="cid" />
            <asp:BoundField DataField="cname" HeaderText="NAME" SortExpression="cname" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:con %>" 
        SelectCommand="SELECT * FROM [category]"
        UpdateCommand="update category set cname=@cname where cid=@cid"
        DeleteCommand="delete from category where cid=@cid"
        ></asp:SqlDataSource>
</td></tr>
</table>
</center>
</asp:Content>

